import { AgentGraph } from './types';

export const AGENT_TEMPLATES: AgentGraph[] = [
  {
    id: 'template_reflection_coder',
    name: '1. Агент-Программист (Reflection Pattern)',
    description: 'Паттерн самокоррекции: одна нейросеть пишет код, вторая (Критик) ищет в нем ошибки, а третья финально исправляет его. Это значительно повышает качество кода.',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    metadata: { version: '1.1.0', tags: ['Agentic', 'Coding', 'Reflection'], runCount: 0 },
    viewport: { x: 0, y: 0, zoom: 0.8 },
    nodes: [
      {
        id: 'in_1',
        type: 'agent_input',
        position: { x: 100, y: 250 },
        data: { label: 'Task Definition', type: 'agent_input', inputs: {}, outputs: {}, settings: { inputType: 'static', initialValue: 'Напиши функцию на Python для парсинга RSS ленты.' } },
      },
      {
        id: 'writer',
        type: 'llm',
        position: { x: 400, y: 250 },
        data: { label: 'Writer (Python Expert)', type: 'llm', inputs: {}, outputs: {}, settings: { systemPrompt: 'You are an expert Python developer. Write clean, efficient code.', temperature: 0.3 } },
      },
      {
        id: 'critic',
        type: 'llm',
        position: { x: 750, y: 100 },
        data: { label: 'Critic (Security & Logic)', type: 'llm', inputs: {}, outputs: {}, settings: { systemPrompt: 'Review the provided Python code for bugs, security issues, and edge cases. List only specific issues.', temperature: 0 } },
      },
      {
        id: 'refiner',
        type: 'llm',
        position: { x: 1100, y: 250 },
        data: { label: 'Refined Writer', type: 'llm', inputs: {}, outputs: {}, settings: { systemPrompt: 'Take the original code and the critique, then produce the final, perfected version of the code.', temperature: 0.2 } },
      },
      {
        id: 'out_1',
        type: 'agent_output',
        position: { x: 1450, y: 250 },
        data: { label: 'Final Code Output', type: 'agent_output', inputs: {}, outputs: {}, settings: {} },
      },
    ],
    edges: [
      { id: 'e1', source: 'in_1', sourceHandle: 'output', target: 'writer', targetHandle: 'input' },
      { id: 'e2', source: 'writer', sourceHandle: 'output', target: 'critic', targetHandle: 'input' },
      { id: 'e3', source: 'writer', sourceHandle: 'output', target: 'refiner', targetHandle: 'input' },
      { id: 'e4', source: 'critic', sourceHandle: 'output', target: 'refiner', targetHandle: 'context' },
      { id: 'e5', source: 'refiner', sourceHandle: 'output', target: 'out_1', targetHandle: 'input' },
    ],
  },
  {
    id: 'template_autonomous_researcher',
    name: '2. Автономный Исследователь (Plan-and-Execute)',
    description: 'Агент разбивает сложный вопрос на части, параллельно собирает информацию через инструменты (Skills) и синтезирует финальный ответ.',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    metadata: { version: '1.1.0', tags: ['Advanced', 'Planning', 'Skills'], runCount: 0 },
    viewport: { x: 0, y: 0, zoom: 0.7 },
    nodes: [
      {
        id: 'in_1',
        type: 'agent_input',
        position: { x: 50, y: 300 },
        data: { label: 'Research Topic', type: 'agent_input', inputs: {}, outputs: {}, settings: { initialValue: 'Сравни эффективность Gemini 1.5 Pro и GPT-4o в кодинге.' } },
      },
      {
        id: 'planner',
        type: 'llm',
        position: { x: 350, y: 300 },
        data: { label: 'Planner (JSON)', type: 'llm', inputs: {}, outputs: {}, settings: { systemPrompt: 'Break the research topic into two specific search queries. Return ONLY JSON: {"q1": "...", "q2": "..."}' } },
      },
      {
        id: 'ext_1',
        type: 'json_extract',
        position: { x: 650, y: 150 },
        data: { label: 'Extract Q1', type: 'json_extract', inputs: {}, outputs: {}, settings: { path: 'q1' } },
      },
      {
        id: 'ext_2',
        type: 'json_extract',
        position: { x: 650, y: 450 },
        data: { label: 'Extract Q2', type: 'json_extract', inputs: {}, outputs: {}, settings: { path: 'q2' } },
      },
      {
        id: 'search_1',
        type: 'skill',
        position: { x: 950, y: 150 },
        data: { label: 'Search Task 1', type: 'skill', inputs: {}, outputs: {}, settings: { skillId: 'url-reader' } },
      },
      {
        id: 'search_2',
        type: 'skill',
        position: { x: 950, y: 450 },
        data: { label: 'Search Task 2', type: 'skill', inputs: {}, outputs: {}, settings: { skillId: 'url-reader' } },
      },
      {
        id: 'merge_1',
        type: 'merge',
        position: { x: 1250, y: 300 },
        data: { label: 'Combine Knowledge', type: 'merge', inputs: {}, outputs: {}, settings: { mergeMode: 'concat_text' } },
      },
      {
        id: 'synthesizer',
        type: 'llm',
        position: { x: 1550, y: 300 },
        data: { label: 'Synthesizer', type: 'llm', inputs: {}, outputs: {}, settings: { systemPrompt: 'Based on the gathered information, write a comprehensive comparison report.' } },
      },
      {
        id: 'out_1',
        type: 'agent_output',
        position: { x: 1850, y: 300 },
        data: { label: 'Final Report', type: 'agent_output', inputs: {}, outputs: {}, settings: {} },
      },
    ],
    edges: [
      { id: 'e1', source: 'in_1', sourceHandle: 'output', target: 'planner', targetHandle: 'input' },
      { id: 'e2_1', source: 'planner', sourceHandle: 'output', target: 'ext_1', targetHandle: 'input' },
      { id: 'e2_2', source: 'planner', sourceHandle: 'output', target: 'ext_2', targetHandle: 'input' },
      { id: 'e3_1', source: 'ext_1', sourceHandle: 'output', target: 'search_1', targetHandle: 'input' },
      { id: 'e3_2', source: 'ext_2', sourceHandle: 'output', target: 'search_2', targetHandle: 'input' },
      { id: 'e4_1', source: 'search_1', sourceHandle: 'output', target: 'merge_1', targetHandle: 'input_a' },
      { id: 'e4_2', source: 'search_2', sourceHandle: 'output', target: 'merge_1', targetHandle: 'input_b' },
      { id: 'e5', source: 'merge_1', sourceHandle: 'output', target: 'synthesizer', targetHandle: 'input' },
      { id: 'e6', source: 'synthesizer', sourceHandle: 'output', target: 'out_1', targetHandle: 'input' },
    ],
  },
  {
    id: 'template_human_in_loop',
    name: '3. Ассистент с Обратной Связью (Human-in-the-Loop)',
    description: 'Агент готовит черновик и приостанавливает выполнение, чтобы спросить пользователя, все ли верно. Если нет — исправляет.',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    metadata: { version: '1.1.0', tags: ['Interactive', 'Feedback', 'Logic'], runCount: 0 },
    viewport: { x: 0, y: 0, zoom: 0.9 },
    nodes: [
      {
        id: 'in_1',
        type: 'agent_input',
        position: { x: 50, y: 200 },
        data: { label: 'Request', type: 'agent_input', inputs: {}, outputs: {}, settings: { initialValue: 'Напиши план статьи про ИИ-агентов.' } },
      },
      {
        id: 'drafter',
        type: 'llm',
        position: { x: 350, y: 200 },
        data: { label: 'Drafter', type: 'llm', inputs: {}, outputs: {}, settings: { systemPrompt: 'Write a detailed draft plan.' } },
      },
      {
        id: 'fb_1',
        type: 'feedback',
        position: { x: 650, y: 200 },
        data: { label: 'User Review', type: 'feedback', inputs: {}, outputs: {}, settings: { promptText: 'Оцените черновик плана. Нужны ли правки?' } },
      },
      {
        id: 'cond_1',
        type: 'condition',
        position: { x: 950, y: 200 },
        data: { label: 'Need Fix?', type: 'condition', inputs: {}, outputs: {}, settings: { conditionCode: 'input.reaction === "dislike"' } },
      },
      {
        id: 'fixer',
        type: 'llm',
        position: { x: 1250, y: 350 },
        data: { label: 'Fixer', type: 'llm', inputs: {}, outputs: {}, settings: { systemPrompt: 'The user requested changes. Update the draft based on their feedback: {{context.feedback_result.message}}' } },
      },
      {
        id: 'merge_1',
        type: 'merge',
        position: { x: 1550, y: 200 },
        data: { label: 'Finalize', type: 'merge', inputs: {}, outputs: {}, settings: { mergeMode: 'first_non_null' } },
      },
      {
        id: 'out_1',
        type: 'agent_output',
        position: { x: 1850, y: 200 },
        data: { label: 'Final Plan', type: 'agent_output', inputs: {}, outputs: {}, settings: {} },
      },
    ],
    edges: [
      { id: 'e1', source: 'in_1', sourceHandle: 'output', target: 'drafter', targetHandle: 'input' },
      { id: 'e2', source: 'drafter', sourceHandle: 'output', target: 'fb_1', targetHandle: 'input' },
      { id: 'e3', source: 'fb_1', sourceHandle: 'feedback_result', target: 'cond_1', targetHandle: 'input' },
      { id: 'e4_yes', source: 'cond_1', sourceHandle: 'condition_true', target: 'fixer', targetHandle: 'input' },
      { id: 'e4_no', source: 'cond_1', sourceHandle: 'condition_false', target: 'merge_1', targetHandle: 'input_a' },
      { id: 'e5', source: 'fixer', sourceHandle: 'output', target: 'merge_1', targetHandle: 'input_b' },
      { id: 'e6', source: 'merge_1', sourceHandle: 'output', target: 'out_1', targetHandle: 'input' },
    ],
  },
  {
    id: 'template_semantic_router',
    name: '4. Семантический Оркестратор (Orchestrator)',
    description: 'Умный диспетчер, который анализирует входные данные и направляет задачу специализированному Саб-агенту (или ветке LLM).',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    metadata: { version: '1.1.0', tags: ['Intermediate', 'Routing', 'Architecture'], runCount: 0 },
    viewport: { x: 0, y: 0, zoom: 0.8 },
    nodes: [
      {
        id: 'in_1',
        type: 'agent_input',
        position: { x: 100, y: 300 },
        data: { label: 'User Query', type: 'agent_input', inputs: {}, outputs: {}, settings: {} },
      },
      {
        id: 'router_llm',
        type: 'router',
        position: { x: 450, y: 300 },
        data: { 
          label: 'Intent Classifier', 
          type: 'router', 
          inputs: {}, 
          outputs: {}, 
          settings: { 
            routerMode: 'llm_classify',
            routeACondition: 'Programming request (coding, bugs, scripts)',
            routeBCondition: 'Creative writing (poems, stories, marketing)',
            routeCCondition: 'Analytical or Logic task (math, data analysis)'
          } 
        },
      },
      {
        id: 'llm_coder',
        type: 'llm',
        position: { x: 850, y: 100 },
        data: { label: 'Specialized Coder', type: 'llm', inputs: {}, outputs: {}, settings: { systemPrompt: 'You are a Senior Developer. Solve the coding task.' } },
      },
      {
        id: 'llm_creative',
        type: 'llm',
        position: { x: 850, y: 300 },
        data: { label: 'Creative Genius', type: 'llm', inputs: {}, outputs: {}, settings: { systemPrompt: 'You are a world-class writer. Be creative and eloquent.' } },
      },
      {
        id: 'llm_analyst',
        type: 'llm',
        position: { x: 850, y: 500 },
        data: { label: 'Data Analyst', type: 'llm', inputs: {}, outputs: {}, settings: { systemPrompt: 'You are a logical analyst. Be precise and data-driven.' } },
      },
      {
        id: 'merge_1',
        type: 'merge',
        position: { x: 1250, y: 300 },
        data: { label: 'Synthesize', type: 'merge', inputs: {}, outputs: {}, settings: { mergeMode: 'first_non_null' } },
      },
      {
        id: 'out_1',
        type: 'agent_output',
        position: { x: 1550, y: 300 },
        data: { label: 'Response', type: 'agent_output', inputs: {}, outputs: {}, settings: {} },
      },
    ],
    edges: [
      { id: 'e1', source: 'in_1', sourceHandle: 'output', target: 'router_llm', targetHandle: 'input' },
      { id: 'e_a', source: 'router_llm', sourceHandle: 'route_a', target: 'llm_coder', targetHandle: 'input' },
      { id: 'e_b', source: 'router_llm', sourceHandle: 'route_b', target: 'llm_creative', targetHandle: 'input' },
      { id: 'e_c', source: 'router_llm', sourceHandle: 'route_c', target: 'llm_analyst', targetHandle: 'input' },
      { id: 'e_ma', source: 'llm_coder', sourceHandle: 'output', target: 'merge_1', targetHandle: 'input_a' },
      { id: 'e_mb', source: 'llm_creative', sourceHandle: 'output', target: 'merge_1', targetHandle: 'input_b' },
      { id: 'e_mc', source: 'llm_analyst', sourceHandle: 'output', target: 'merge_1', targetHandle: 'input_c' },
      { id: 'e_out', source: 'merge_1', sourceHandle: 'output', target: 'out_1', targetHandle: 'input' },
    ],
  }
];
